version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      codeql-action-version-updates:
        applies-to: version-updates
        patterns:
          - "github/codeql-action/*"
      codeql-action-security-updates:
        applies-to: security-updates
        patterns:
          - "github/codeql-action/*"
    labels:
      - dependencies
      - github-actions
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - npm
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python
