[CmdletBinding()]
param(
    [string]$RepoRoot,
    [string]$RuntimeRoot,
    [string]$PythonCommand,
    [string[]]$Skill,
    [ValidateSet("none", "sections", "full")]
    [string]$Validate = "none",
    [switch]$SkipInstall
)

# Single public entrypoint for Ceratops skill install/update checks.
#
# This PowerShell layer owns user-facing orchestration: resolving the source
# repo, choosing Python, validating requested skill names, optionally rebuilding
# installed skill copies, and optionally running consistency validation. The
# Python files remain narrow implementation modules: build-runtime-skills.py
# renders/copies runtime skills, and validate-skills-consistency.py checks the
# source model. Keeping those modules separate avoids one large script while
# preserving one command for humans and skills.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

if (-not $SkipInstall -and [string]::IsNullOrWhiteSpace($RuntimeRoot)) {
    $codexHome = $env:CODEX_HOME
    if ([string]::IsNullOrWhiteSpace($codexHome)) {
        $homeRoot = $env:USERPROFILE
        if ([string]::IsNullOrWhiteSpace($homeRoot)) {
            $homeRoot = $env:HOME
        }
        if ([string]::IsNullOrWhiteSpace($homeRoot)) {
            throw "Could not resolve a home directory. Set CODEX_HOME or pass -RuntimeRoot."
        }
        $codexHome = Join-Path $homeRoot ".codex"
    }
    $RuntimeRoot = Join-Path $codexHome "skills"
}

function Resolve-PythonCommand {
    param([string]$Preferred)

    # Prefer a caller-provided interpreter, then normal launcher names. The
    # skill installer intentionally avoids environment activation so the runtime
    # copy can be rebuilt from a plain shell or automation task.
    if (-not [string]::IsNullOrWhiteSpace($Preferred) -and (Test-Path -LiteralPath $Preferred)) {
        return (Resolve-Path -LiteralPath $Preferred).Path
    }

    foreach ($candidate in @($Preferred, "python", "py")) {
        if ([string]::IsNullOrWhiteSpace($candidate)) {
            continue
        }
        $command = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($null -ne $command) {
            if ($command.Source) {
                return $command.Source
            }
            if ($command.Path) {
                return $command.Path
            }
            return $command.Name
        }
    }

    throw "Could not find a usable Python command. Install Python or pass -PythonCommand."
}

$resolvedRepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
$skillsRoot = Join-Path $resolvedRepoRoot "skills"
$builder = Join-Path $resolvedRepoRoot "scripts\build-runtime-skills.py"
$validator = Join-Path $resolvedRepoRoot "scripts\validation\validate-skills-consistency.py"
if (-not (Test-Path -LiteralPath $skillsRoot -PathType Container)) {
    throw "Missing skills directory: $skillsRoot"
}
if (-not (Test-Path -LiteralPath $builder -PathType Leaf)) {
    throw "Missing runtime skill builder: $builder"
}
if ($Validate -ne "none" -and -not (Test-Path -LiteralPath $validator -PathType Leaf)) {
    throw "Missing skill consistency validator: $validator"
}

$python = Resolve-PythonCommand $PythonCommand
$sourceSkillNames = Get-ChildItem -LiteralPath $skillsRoot -Directory |
    Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName "SKILL.md") } |
    Sort-Object Name |
    ForEach-Object { $_.Name }

$buildSkillNames = @()
if ($null -ne $Skill -and $Skill.Count -gt 0) {
    $known = @{}
    foreach ($skillName in $sourceSkillNames) {
        $known[$skillName] = $true
    }
    foreach ($skillName in $Skill) {
        if (-not $known.ContainsKey($skillName)) {
            throw "Unknown skill: $skillName"
        }
        $buildSkillNames += $skillName
    }
} else {
    $buildSkillNames = $sourceSkillNames
}

if (-not $SkipInstall) {
    if (-not (Test-Path -LiteralPath $RuntimeRoot)) {
        New-Item -ItemType Directory -Path $RuntimeRoot | Out-Null
    }

    $builderArgs = @($builder, "--runtime-root", $RuntimeRoot)
    foreach ($skillName in $buildSkillNames) {
        $builderArgs += @("--skill", $skillName)
    }
    if ($buildSkillNames.Count -eq $sourceSkillNames.Count) {
        # Full installs can remove stale folders previously generated by the builder.
        # Targeted installs leave unrelated managed skills alone for active previews.
        $builderArgs += "--remove-stale"
    }

    $buildOutput = & $python @builderArgs 2>&1
    if ($LASTEXITCODE -ne 0) {
        if ($buildOutput) {
            $buildOutput | ForEach-Object { Write-Error $_ }
        }
        throw "Runtime skill build failed."
    }

    Write-Output "installed"
}

if ($Validate -ne "none") {
    $validatorArgs = @($validator)
    if ($Validate -eq "sections") {
        $validatorArgs += @("--mode", "sections")
    }

    $validationOutput = & $python @validatorArgs 2>&1
    if ($LASTEXITCODE -ne 0) {
        if ($validationOutput) {
            $validationOutput | ForEach-Object { Write-Error $_ }
        }
        throw "Skill consistency validation failed."
    }
    if ($validationOutput) {
        $validationOutput | ForEach-Object { Write-Output $_ }
    }
    Write-Output "validated:$Validate"
}
